[features]
seeds = false
skip-lint = false
[programs.localnet]
encode_programs = "5VTgsSmeqpsMsEcvP8611oLoxi3FHMNcJ884Jhto5wFU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/beeman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
